### ISSUE TITLE
Normalize focus outline for editable

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-editor-classic#27]
As in https://github.com/CKEditor5/ckeditor5.github.io/issues/14.

We need a different indication of the focus (or none).

**Comment by Reinmar** [comment]
After this issue is fixed we can revert this: https://github.com/CKEditor5/ckeditor5.github.io/pull/15.

**Comment by fredck** [comment]
I would go for "none".

**Comment by Reinmar** [comment]
This is interesting – see how Chrome is losing the focus outline in certain cases :D

![sep-28-2016 14-35-54](https://cloud.githubusercontent.com/assets/156149/18913618/f661a19c-8588-11e6-936e-3fc7bebca0ec.gif)

Perhaps it's a bug with how the features work, cause perhaps they should focus the editable explicitly when executed. I guess that only the heading feature does that.

**Comment by Reinmar** [comment]
I reported an issue for the above: https://github.com/ckeditor/ckeditor5/issues/338.

**Comment by oleq** [comment]
I decided that CKEditor 5, being yet another form component must clearly indicate the focus, just like other fields (inputs, selects, etc.) when users navigate the form. It's a matter of accessibility and consistency. CKEditor is not a standalone application but a part of an ecosystem (i.e. blog post form, forum post form, etc.).

https://github.com/ckeditor/ckeditor5-theme-lark/issues/50 should solve the problem with focus outline being cropped or disappearing.

**Comment by oleq** [comment]
https://github.com/ckeditor/ckeditor5-theme-lark/issues/50 solved the issue.

**Comment by Reinmar** [comment]
Chrome:

![image](https://cloud.githubusercontent.com/assets/156149/20561682/0acf6074-b180-11e6-8567-8a636f69d17b.png)

Firefox:

![image](https://cloud.githubusercontent.com/assets/156149/20561699/1bba4e6c-b180-11e6-97e7-af2e7e05502f.png)

Safari:

![image](https://cloud.githubusercontent.com/assets/156149/20561718/3b304044-b180-11e6-9a98-ce763c6d7114.png)

I think it's ok now. I'm just a bit unsure whether a totally different kind of outline in Firefox is ok. I think you tried to align it to its native styles, but native input styling looks (at least in JSFiddle) like this:

![image](https://cloud.githubusercontent.com/assets/156149/20561793/9c5fc5ec-b180-11e6-9330-1998eef69f04.png)

**Comment by Reinmar** [comment]
> I think you tried to align it to its native styles, but native input styling looks (at least in JSFiddle) like this:

I didn't put that clearly – contentEditable elements have dotted outline by default... or at least I remember that. When I'm checking it now it has blue outline as well. So either they changed something or apparently both of us have a bad memory :d.

**Comment by oleq** [comment]
Firefox is inconsistent in terms of styling. Inputs have blue "outline" there but contenteditable and buttons get a dotted outline. 

It's weird, I checked it but I didn't quite get what type of "outline" is set to the inputs (couldn't find it in inspector) so I decided to not to deal with the problem right now, especially considering market share of the browser.

**Comment by Reinmar** [comment]
Doh, I tested in Chrome now :D. This is cE in FF:

![image](https://cloud.githubusercontent.com/assets/156149/20561976/98672934-b181-11e6-86a5-f0930a77416a.png)

**Comment by oleq** [comment]
Anyway, generally speaking, I'd rather [not change the UA styles](https://www.tjvantoll.com/2013/01/28/stop-messing-with-the-browsers-default-focus-outline/), for various reasons (they're expected by the users, they change, they need to be maintained, bugs, etc.).

**Comment by Reinmar** [comment]
It's still over 10% globally and far more in some countries. I think that if we have to set any outline (and we do) it'd make sense to hardcode this color (if there's no predefined CSS color name for it).

In fact, the same color will be needed for widget outlines so the .scss file with colors should expose it.

**Comment by Reinmar** [comment]
> Anyway, generally speaking, I'd rather not change the UA styles, for various reasons (they're expected by the users, they change, they need to be maintained, bugs, etc.)

But the user may expect the cE to be styled as an input. The user will not know that the editor is not a textarea. So the current solution is confusing, because the dotted style doesn't match input and textarea styles.

**Comment by fredck** [comment]
> I decided that CKEditor 5, being yet another form component must clearly indicate the focus, just like other fields (inputs, selects, etc.) when users navigate the form.

I don't agree with this. Neither that we must force the style of it (by default, ofc) or that it is "yet another form component".

In fact, https://github.com/CKEditor5/ckeditor5.github.io/issues/14 has been opened and fixed right because of that assumption.

An extra complication with this is that, if we really want to make the "editor" outlined, at this point, the whole component should be highlighted, not only part of it. For instance, the toolbar is not highlighted together with the editable.

I would, again, opt to go for "none".

**Comment by oleq** [comment]
> or that it is "yet another form component".
What is CKEditor then?

**Comment by fredck** [comment]
> What is CKEditor then?

CKEditor 0.8 was a "replacement for textareas". CKEditor 5 is whatever you want.

> We don't. Only what gets focus should be outlined (editable, buttons, inputs).

I would agree, as long as the toolbar would not be connected to the editable. For example, there is a clear detachment between the textarea and the toolbar in the field I'm using right now in GH for this comment.

Anyway, I'm just leaving here my impression. The PR you provided for this doesn't fix this issue. If that's the way to go this issue should be closed as "invalid", not "fixed".

**Comment by Reinmar** [comment]
> CKEditor 0.8 was a "replacement for textareas". CKEditor 5 is whatever you want.

By "you" I guess you meant "a developer". And this is true, of course, but that doesn't mean that the default implementation should be as generic as "whatever". After all, in 99% of cases, the editor will be a place to type a text and such places have outlines when focused (if correctly styled). Even the editor in which I'm typing now, even Twitter. And if "you" are Facebook and want to achieve this:

![image](https://cloud.githubusercontent.com/assets/156149/20565966/d20c30e6-b193-11e6-965a-ca8bc6c07c2c.png)

You can always change or override the theme.

**Comment by Reinmar** [comment]
Huh... I still think the idea that CKEditor is just one of text fields and hence deserves some focus indicator was quite right, but I must say that this looks bad:

![image](https://cloud.githubusercontent.com/assets/156149/20720471/8e7d0b68-b65f-11e6-8cc1-a000f988b81c.png)

It's too much happening there. So, my second thought is that if we want to indicate the focus by default, then perhaps the style must be lighter (e.g. just a small change in border color?). If that's not ok with you (cause it's not the OS default), @oleq, then I'd vote for not indicating the outline. There's a pretty good reason why most apps override the native styles and this is that they are pretty distracting (as we can see on ckeditor.github.io).

**Comment by fredck** [comment]
Re+1 to have no styling.

**Comment by oleq** [comment]
@Reinmar The styles you mentioned are distracting because what we do on github.io has nothing to do with the reality of WYSIWYG editor integrations. We showcase editor as a main element of the web page, huge and contrasty, especially because the background of the web page is black. 

In reality, this would be a sad, gray CMS form with a couple of inputs and CKEditor to write a post. Then what you see in the screenshot would make sense.

I think it's more a matter of styling focus outlines to match the look and feel of our github.io page than getting rid of them.

**Comment by Reinmar** [comment]
> In reality, this would be a sad, gray CMS form with a couple of inputs and CKEditor to write a post. Then what you see in the screenshot would make sense.

The problem that I saw on ckeditor5.gh.io was the combination of widget outline and editor outline. There should be only one outline at the same time. This is not going to change in a grey CMS. There will be even more conflicts as we add tables and more widgets and the blue colour will be everywhere.

So for me there are only two options still – no styling (as Fred proposes) or very delicate styling just to indicate the "active" state and to not conflict with the focus state.
