### ISSUE TITLE
Editable needs padding

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-editor-classic#28]
Editable needs some padding:

![screen shot 2016-09-13 at 13 19 47](https://cloud.githubusercontent.com/assets/156149/18472000/effa6b66-79b4-11e6-97a5-e2795267b69a.png)

This will look bad in many scenarios, so I guess that by default it should have a padding. It's natural that developers style block to have only bottom margins so we cannot rely on this.

**Comment by oleq** [comment]
@Reinmar Is the issue still valid? I suppose not because I haven't seen such problems for a while and there's also this [padding](https://github.com/ckeditor/ckeditor5-editor-classic/blob/master/theme/theme.scss#L42) in [each theme file](https://github.com/ckeditor/ckeditor5-theme-lark/issues/97).

**Comment by Reinmar** [comment]
Hm... I didn't encounter this issue recently too, so let's close it.

**Comment by Reinmar** [comment]
In fact, it's more "invalid" than "fixed".
