### ISSUE TITLE
 help activate options on toolbar

### ISSUE THREAD

**Issue by GlauberF** [ckeditor/ckeditor5-editor-classic#86]
I'm using ckeditor 5, with the component for angular.

I can not find in
documentation how to activate:

1 - text color
2 - background color
3 - view source
4 - font size
5 - make insert from an image to base64, in the content

If you can help me, show example with code, thank you.

I found the documentation very confusing.

**Comment by Mgsy** [comment]
Hi, you can find all the available plugins in the [features section](https://ckeditor.com/docs/ckeditor5/latest/features/). From the list of plugins you want to activate, only [font plugin](https://ckeditor.com/docs/ckeditor5/latest/features/) is officially released.

Anyway, text color and background color features are under development (PR is on the review), so you can track the progress [here](https://github.com/ckeditor/ckeditor5/issues/1457).

According to the view source - we have a [proper ticket ](https://github.com/ckeditor/ckeditor5/issues/592)for this one.

If you have any feature request, feel free to create a new issue and describe your use case.
