### ISSUE TITLE
ClassicEditor not working on iPad 4th generation iOS 10

### ISSUE THREAD

**Issue by fredemagi** [ckeditor/ckeditor5-editor-classic#88]
I cannot get the ClassicEditor to work on iPad 4th generation with iOS 10. I simply leaves the textarea as is. The code looks like: 
`ClassicEditor.create(document.querySelector('.textarea-reply'), 
{
  toolbar: [ 'bold', 'italic', 'bulletedList', 'numberedList']
} );`

**Comment by Mgsy** [comment]
Hi, are you able to share errors which appear in the console? Besides that, did you check whether it works properly on a desktop?

**Comment by fredemagi** [comment]
Hi @Mgsy,

It works well on my iPhone 7 with newest version of iOS. It works well too on desktop. However, it yields this error in the console: `Uncaught (in promise) TypeError: Cannot read property 'style' of null
    at ah.replace (ckeditor.js:1)
    at n.initPlugins.then.then (ckeditor.js:1)`

**Comment by Mgsy** [comment]
Actually, Safari on iOS 10 contains a critical bug in JS parser, so unfortunately, it won't be possible to run CKEditor 5 on a device using this OS version. 

However, you could transpile the code to ES5 what should solve the problem. [Here](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/advanced-setup.html#option-building-to-es5-target) is a guide on how to do it. 

Reading a discussion from this ticket might be also helpful - https://github.com/ckeditor/ckeditor5/issues/542.

**Comment by fredemagi** [comment]
@Mgsy,

Thank you. I will take a look at the guide :).
