### ISSUE TITLE
Can't find ckeditor.js file

### ISSUE THREAD

**Issue by omotayo89** [ckeditor/ckeditor5-editor-classic#91]
I am trying to follow this tutorial https://ckeditor.com/docs/ckeditor5/latest/features/collaboration/comments/comments-integration.html but can't find the ckeditor.js file. please help

**Comment by Mgsy** [comment]
`ckeditor.js` is inside `src` directory in the cloned repository.

![image](https://user-images.githubusercontent.com/20988892/59360217-fe3e8400-8d2f-11e9-84a2-bb4b9819f073.png)
